site_name: JavaScript - Estudo

markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme: 
  name: material
  language: pt
  palette:
    scheme: slate
    primary: yellow
  logo: "assets/logo2.png"
  features: 
    - navigation.tabs.sticky
    - content.code.annotate
    - navigation.expand
    - navigation.indexes
  icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16

extra: 
  consent:
    title: Consetimento de Cookies
    description: >- 
      Usamos cookies para reconhecer suas visitas e preferências repetidas, bem como para medir a eficácia de nossa documentação e se os usuários encontram o que procuram. Com o seu consentimento, você está nos ajudando a melhorar nossa documentação.



    

nav:
    - Introdução: index.md
    - Parte 1(Inicio):
      - Variáveis: parte1/variaveis.md
      - Números e Operadores: parte1/numero.md
      - Boolean e Condicionais: parte1/boolean.md
      - Funções: parte1/funcoes.md
      - Objeto: parte1/objeto.md



  